name: dummy

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  dummy:
    name: Show python version and executable
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup python
      uses: actions/setup-python@v4

    - name: Show python version
      run: |
        python -V
        python -c "import sys; print(sys.executable)"
