name: python-format

on: [pull_request]

jobs:
  format:
    name: Format Python Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Find changed files certain types handle removals
      run: |
        echo Working from branch ${{ github.head_ref }}
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git fetch --prune origin
        git checkout ${{ github.head_ref }}
        "touched_files = git diff --name-only --diff-filter=ACMRTUXB origin/main" >> $GITHUB_EN
        "touched_py_files = git diff --name-only --diff-filter=ACMRTUXB origin/main | grep -E "(.py$)"" >> $GITHUB_EN
        echo {{ env.touched_files }}
        echo {{ env.touched_py_files }}

    # - name: Run isort
    #   run: |
    #     pip install isort
    #     isort . --profile black

    # - name: Run black
    #   run: |
    #     pip install black
    #     black . -l 100

    # - name: Find changed files certain types handle removals
    #   run: |
    #     echo Working from branch ${{ github.head_ref }}
    #     git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
    #     git config --global user.name "github-actions[bot]"
    #     git fetch --prune origin
    #     git checkout ${{ github.head_ref }}
    #     git diff --name-only --diff-filter=ACMRTUXB origin/main | grep -E "(.py$)"


    # - name: Commit updates
    #   run: |
    #     echo Working from branch ${{ github.head_ref }}
    #     git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
    #     git config --global user.name "github-actions[bot]"
    #     git fetch --prune origin
    #     git checkout ${{ github.head_ref }}
    #     git add .
    #     git commit -m "[github-action] auto format from format.yml action"
    #     git push

    # - name: Ensure repo status is clean
    #   run: git status
