name: python-format

on: [pull_request]

jobs:
  format:
    name: Format Python Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup GitHub actions bot
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Setup python
      uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    # Created env vars will not be available in the job in which
    # they are created. The action that creates or updates the
    # environment variable does not have access to the new value, but
    # all subsequent actions in a job will have access. Env vars are
    # case-sensitive and you can include punctuation.
    - name: Store PR touched files (ignored deleted files)
      run: |
        echo Working from branch ${{ github.head_ref }}
        git fetch --prune origin
        git checkout ${{ github.head_ref }}
        echo "touched_files=$(git diff --name-only --diff-filter=ACMRTUXB origin/main | tr -s '\n' ' ')" >> $GITHUB_ENV
        echo "touched_py_files=$(git diff --name-only --diff-filter=ACMRTUXB origin/main | grep -E .py$ | tr -s '\n', ' ')" >> $GITHUB_ENV

    - name: Report PR touched files
      run: |
        echo "All touched files: ${{ env.touched_files }}"
        echo "Python (.py) touched files: ${{ env.touched_py_files }}"

    - name: Check isort on python (.py) touched files
      if: ${{ env.touched_py_files != null }}
      run: |
        pip install isort
        isort --check -q ${{ env.touched_py_files }} --profile black
        echo "isort_updates_needed=$?" >> $GITHUB_ENV
      continue-on-error: true

    - name: Run isort on python (.py) touched files
      if: ${{ env.touched_py_files != null && env.isort_updates_needed == 1 }}
      run: |
        isort ${{ env.touched_py_files }} --profile black

    - name: Check black on python (.py) touched files
      if: ${{ env.touched_py_files != null }}
      run: |
        pip install black
        black --check -q ${{ env.touched_py_files }} -l 100
        echo "black_updates_needed=$?" >> $GITHUB_ENV
      continue-on-error: true

    - name: Run black on python (.py) touched files
      if: ${{ env.touched_py_files != null && env.black_updates_needed == 1 }}
      run: |
        black ${{ env.touched_py_files }} -l 100

    - name: Commit and push updates to PR
      #if: ${{ env.isort_updates_made == 1 || env.black_updates_made == 1 }}
      if: ${{ env.touched_py_files != null && (env.isort_updates_needed ==1 || env.black_updates_need == 1) }}
      run: |
        echo Working from branch ${{ github.head_ref }}
        git checkout ${{ github.head_ref }}
        git add .
        git commit -m "[github-action] auto-format: isort and black"
        git push

    - name: Ensure repo status is clean
      run: git status
