name: python-format

on: [pull_request]

jobs:
  format:
    name: Format Python Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run isort
      run: |
        pip install isort
        isort . --profile black

    - name: Run black
      run: |
        pip install black
        black . -l 100

    - name: Commit updates
      run: |
        echo Working from branch ${{ github.head_ref }}
        git config --global user.email "git@github.com"
        git config --global user.name "GitHub Bot"
        git fetch --prune origin
        git checkout ${{ github.head_ref }}
        git add .
        git commit -m "[github-action] auto format from format.yml action"
        git push

    - name: Ensure repo status is clean
      run: git status
